- name: Stop hpaq
  import_playbook: ../artifact_playbooks/dev_hpdaq_stop.yml

- import_playbook: ../artifact_playbooks/dev_hpdaq_set_system.yml
  vars:
    system: "vla_ibv"

- name: Recompile hpaq
  import_playbook: ../artifact_playbooks/dev_hpdaq_recompile.yml
  vars:
    payload_reorder: "ATA_PAYLOAD_TRANSPOSE_FTP"
    databuffer_size: "32*64*131072*2*2"

- name: Start all hpdaq instances
  import_playbook: ../artifact_playbooks/dev_hpdaq_start.yml