- name: Stop hpaq
  import_playbook: ../artifact_playbooks/dev_hpdaq_stop.yml

- name: Recompile XGPU
  import_playbook: ../artifact_playbooks/dev_xgpu_recompile.yml
  vars:
    ntime: 32768
    nfreq: 64
    nant: 32

- name: Recompile hpaq
  import_playbook: ../artifact_playbooks/dev_hpdaq_recompile.yml
  vars:
    payload_reorder: "ATA_PAYLOAD_TRANSPOSE_TFP_DP4A"
    databuffer_size: "32*64*32768*2*2"

- import_playbook: ../artifact_playbooks/dev_hpdaq_set_system.yml
  vars:
    system: "vla_xgpu"

- name: Start all hpdaq instances
  import_playbook: ../artifact_playbooks/dev_hpdaq_start.yml