- name: Stop hpaq
  import_playbook: ../artifact_playbooks/hpdaq_stop.yml

- name: Reconfigure Hpdaq for BLADE ModeF
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "channelizer_rate"
      prompt: "Channelizer rate"
      default: "128"
      private: no
  tasks:
    - name: Stash channelizer_rate
      add_host:
        name: "variable_holder"
        channelizer_rate:  "{{ channelizer_rate }}"

- name: Reconfigure Hpdaq for BLADE ModeF
  hosts: cosmic-gpu-0
  tasks:
    - name: Define BLADE_MODE_F_CHANNELIZER_RATE as '{{ hostvars.variable_holder.channelizer_rate }}' in hpguppi_blade_mode_f_config.h
      lineinfile:
          dest: /home/cosmic/dev/hpdaq/src/hpguppi_blade_mode_f_config.h
          state: present
          regexp: '^#define BLADE_MODE_F_CHANNELIZER_RATE.*'
          line: '#define BLADE_MODE_F_CHANNELIZER_RATE {{ hostvars.variable_holder.channelizer_rate }} // [1, 4]; <= 1 mitigates the channlisation'

- name: Recompile XGPU
  import_playbook: ../artifact_playbooks/xgpu_recompile.yml
  vars:
    channelizer_rate: "{{ hostvars['variable_holder']['channelizer_rate'] }}"
    ntime: "{{ (32768 / channelizer_rate|int)|int }}"
    nfreq: "{{ 128 * channelizer_rate|int }}"
    nant: 16

- name: Recompile hpaq
  import_playbook: ../artifact_playbooks/hpdaq_recompile.yml
  vars:
    payload_reorder: "ATA_PAYLOAD_TRANSPOSE_FTP"
    databuffer_size: "16*128*32768*2*2"

- name: Rewrite INSTANCE_SYSTEM_NAME in /home/cosmic/dev/hpdaq/hpguppi_service.conf
  import_playbook: ../artifact_playbooks/hpdaq_set_system.yml
  vars:
    system: "vla_finecorr"

- name: Start all hpdaq instances
  import_playbook: ../artifact_playbooks/hpdaq_start.yml