- name: Stop hpaq
  import_playbook: ../artifact_playbooks/hpdaq_stop.yml

- name: Rewrite INSTANCE_SYSTEM_NAME in /home/cosmic/hpguppi_service.conf
  import_playbook: ../artifact_playbooks/hpdaq_set_system.yml
  vars:
    system: "vla_ibv"

- name: Recompile hpaq
  import_playbook: ../artifact_playbooks/hpdaq_recompile.yml
  vars:
    payload_reorder: "ATA_PAYLOAD_TRANSPOSE_FTP"
    databuffer_size: "32*32*131072*2*2"

- name: Start all hpdaq instances
  import_playbook: ../artifact_playbooks/hpdaq_start.yml