- name: Recompile XGPU at /home/cosmic/src/xGPU/src
  hosts: cosmic-gpu-0
  # become: yes
  gather_facts: no

  tasks:
    - name: Recompile xGPU (NTIME={{ ntime }} NFREQUENCY={{ nfreq }} NSTATION={{ nant }})
      shell:
        chdir: /home/cosmic/src/xGPU/src
        cmd: make clean && make NTIME={{ ntime }} NTIME_PIPE=128 NPOL=2 NFREQUENCY={{ nfreq }} NSTATION={{ nant }} CUDA_ARCH=sm_86 DP4A=yes

    # - name: Install xGPU
    #   shell:
    #     chdir: /home/cosmic/src/xGPU/src
    #     cmd: make install
