- name: Rewrite INSTANCE_SYSTEM_NAME={{ system }} in /home/cosmic/hpguppi_service.conf
  hosts: cosmic-gpu-0
  # become: yes
  gather_facts: no
  
  tasks:
      - lineinfile:
          dest: /home/cosmic/hpdaq_service.conf
          state: present
          regexp: '^INSTANCE_SYSTEM_NAME=.*'
          line: 'INSTANCE_SYSTEM_NAME={{ system }}'